import type { OfficerUser, OfficerRole, Permission } from '../types/auth';

export interface DemoUserAccount extends OfficerUser {
  passwordHash: string; // Stored demo password for prototype login
}

export const DEMO_ACCOUNTS: DemoUserAccount[] = [
  {
    id: 'OFFICER-NAT-001',
    name: 'Rajesh V. Sharma',
    email: 'admin@kshetra.gov.in',
    role: 'NATIONAL_ADMIN',
    roleTitle: 'National Administrator',
    department: 'Ministry of Infrastructure & Land Acquisition',
    jurisdictionScope: 'INDIA',
    badgeId: 'GOV-IN-8842',
    isDemoAccount: true,
    avatarInitials: 'RS',
    passwordHash: 'kshetra2026',
  },
  {
    id: 'OFFICER-ST-027',
    name: 'Priya N. Deshmukh',
    email: 'mh.officer@kshetra.gov.in',
    role: 'STATE_OFFICER',
    roleTitle: 'State Nodal Officer',
    department: 'Maharashtra Revenue & Forest Dept',
    jurisdictionScope: 'STATE',
    state: 'Maharashtra',
    badgeId: 'GOV-MH-5120',
    isDemoAccount: true,
    avatarInitials: 'PD',
    passwordHash: 'kshetra2026',
  },
  {
    id: 'OFFICER-DT-104',
    name: 'Vikram Singh Patil',
    email: 'nashik.do@kshetra.gov.in',
    role: 'DISTRICT_OFFICER',
    roleTitle: 'District Collector / SLAO',
    department: 'District Collectorate, Nashik',
    jurisdictionScope: 'DISTRICT',
    state: 'Maharashtra',
    district: 'Nashik',
    badgeId: 'GOV-NSK-3041',
    isDemoAccount: true,
    avatarInitials: 'VP',
    passwordHash: 'kshetra2026',
  },
  {
    id: 'OFFICER-PO-902',
    name: 'Anil Kumar Mehta',
    email: 'po.la1842@kshetra.gov.in',
    role: 'PROJECT_OFFICER',
    roleTitle: 'Special Land Acquisition Officer',
    department: 'NHAI Highway Project Unit',
    jurisdictionScope: 'ASSIGNED',
    state: 'Maharashtra',
    assignedProjects: ['LA-1842', 'LA-1931'],
    badgeId: 'GOV-PO-1842',
    isDemoAccount: true,
    avatarInitials: 'AM',
    passwordHash: 'kshetra2026',
  },
  {
    id: 'OFFICER-MO-401',
    name: 'Suresh Chandra Verma',
    email: 'monitoring@kshetra.gov.in',
    role: 'MONITORING_OFFICER',
    roleTitle: 'Monitoring Officer',
    department: 'PMO Project Monitoring Group (PMG)',
    jurisdictionScope: 'INDIA',
    badgeId: 'GOV-PMO-9912',
    isDemoAccount: true,
    avatarInitials: 'SV',
    passwordHash: 'kshetra2026',
  },
  {
    id: 'OFFICER-RO-007',
    name: 'Dr. Sunita Rao',
    email: 'auditor@kshetra.gov.in',
    role: 'READ_ONLY',
    roleTitle: 'Governance Auditor',
    department: 'CAG Infrastructure Audit Division',
    jurisdictionScope: 'VIEW_ONLY',
    badgeId: 'GOV-AUD-7701',
    isDemoAccount: true,
    avatarInitials: 'SR',
    passwordHash: 'kshetra2026',
  },
];

export const ROLE_PERMISSIONS: Record<OfficerRole, Permission[]> = {
  NATIONAL_ADMIN: [
    'VIEW_NATIONAL_DASHBOARD',
    'VIEW_PROJECTS',
    'VIEW_PROJECT_DETAILS',
    'VIEW_PREDICTIONS',
    'VIEW_WARNINGS',
    'REVIEW_ACTIONS',
    'EXECUTE_ACTION',
    'VIEW_AUDIT',
    'MANAGE_PROJECTS',
    'MANAGE_OFFICERS',
    'EXPORT_REPORTS',
  ],
  STATE_OFFICER: [
    'VIEW_NATIONAL_DASHBOARD',
    'VIEW_PROJECTS',
    'VIEW_PROJECT_DETAILS',
    'VIEW_PREDICTIONS',
    'VIEW_WARNINGS',
    'REVIEW_ACTIONS',
    'EXECUTE_ACTION',
    'VIEW_AUDIT',
    'EXPORT_REPORTS',
  ],
  DISTRICT_OFFICER: [
    'VIEW_NATIONAL_DASHBOARD',
    'VIEW_PROJECTS',
    'VIEW_PROJECT_DETAILS',
    'VIEW_PREDICTIONS',
    'VIEW_WARNINGS',
    'REVIEW_ACTIONS',
    'EXECUTE_ACTION',
    'EXPORT_REPORTS',
  ],
  PROJECT_OFFICER: [
    'VIEW_PROJECTS',
    'VIEW_PROJECT_DETAILS',
    'VIEW_PREDICTIONS',
    'VIEW_WARNINGS',
    'REVIEW_ACTIONS',
    'EXECUTE_ACTION',
  ],
  MONITORING_OFFICER: [
    'VIEW_NATIONAL_DASHBOARD',
    'VIEW_PROJECTS',
    'VIEW_PROJECT_DETAILS',
    'VIEW_PREDICTIONS',
    'VIEW_WARNINGS',
    'REVIEW_ACTIONS',
    'EXECUTE_ACTION',
    'VIEW_AUDIT',
    'EXPORT_REPORTS',
  ],
  READ_ONLY: [
    'VIEW_NATIONAL_DASHBOARD',
    'VIEW_PROJECTS',
    'VIEW_PROJECT_DETAILS',
    'VIEW_PREDICTIONS',
    'VIEW_WARNINGS',
    'VIEW_AUDIT',
  ],
};
